"use client";
import { useEffect, useState } from "react";
import { Sparkles } from "lucide-react";
import { api } from "@/lib/api";
import { useAudience } from "@/lib/audience";
import { usePeriod } from "@/lib/period";

interface InsightResponse { content: string | null; model: string | null; cached: boolean; error?: string }

export default function InsightCard({ section }: { section: string }) {
  const { audience } = useAudience();
  const { period } = usePeriod();
  const [data, setData] = useState<InsightResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    api<InsightResponse>(`/api/insights/${audience}/${section}?period=${period}`)
      .then(setData).catch(() => setData(null)).finally(() => setLoading(false));
  }, [audience, section, period]);

  return (
    <div className="panel border-l-2 border-l-[var(--accent)] p-5">
      <p className="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-[var(--muted)]">
        <Sparkles className="h-3.5 w-3.5 text-[var(--accent)]" /> Commentary · {audience} view
      </p>
      {loading ? (
        <p className="subtle animate-pulse">Generating fact-grounded commentary…</p>
      ) : data?.content ? (
        <>
          <p className="text-sm leading-relaxed">{data.content}</p>
          <p className="subtle mt-3 text-xs">
            Generated by {data.model} from validated facts only · every number verified against the database before display
          </p>
        </>
      ) : (
        <p className="subtle text-sm">{data?.error ?? "Commentary unavailable."}</p>
      )}
    </div>
  );
}
